// Code generated by MockGen. DO NOT EDIT.
// Source: cache.go
//
// Generated by this command:
//
//	mockgen -source=cache.go -destination=../mocks/repository/cache.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	domain "pastebin/internal/domain/repository"
	models "pastebin/internal/models"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockCache is a mock of Cache interface.
type MockCache struct {
	ctrl     *gomock.Controller
	recorder *MockCacheMockRecorder
	isgomock struct{}
}

// MockCacheMockRecorder is the mock recorder for MockCache.
type MockCacheMockRecorder struct {
	mock *MockCache
}

// NewMockCache creates a new mock instance.
func NewMockCache(ctrl *gomock.Controller) *MockCache {
	mock := &MockCache{ctrl: ctrl}
	mock.recorder = &MockCacheMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCache) EXPECT() *MockCacheMockRecorder {
	return m.recorder
}

// Pasta mocks base method.
func (m *MockCache) Pasta() domain.PastaCache {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Pasta")
	ret0, _ := ret[0].(domain.PastaCache)
	return ret0
}

// Pasta indicates an expected call of Pasta.
func (mr *MockCacheMockRecorder) Pasta() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Pasta", reflect.TypeOf((*MockCache)(nil).Pasta))
}

// MockPastaCache is a mock of PastaCache interface.
type MockPastaCache struct {
	ctrl     *gomock.Controller
	recorder *MockPastaCacheMockRecorder
	isgomock struct{}
}

// MockPastaCacheMockRecorder is the mock recorder for MockPastaCache.
type MockPastaCacheMockRecorder struct {
	mock *MockPastaCache
}

// NewMockPastaCache creates a new mock instance.
func NewMockPastaCache(ctrl *gomock.Controller) *MockPastaCache {
	mock := &MockPastaCache{ctrl: ctrl}
	mock.recorder = &MockPastaCacheMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPastaCache) EXPECT() *MockPastaCacheMockRecorder {
	return m.recorder
}

// AddMeta mocks base method.
func (m *MockPastaCache) AddMeta(ctx context.Context, pasta *models.Pasta) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddMeta", ctx, pasta)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddMeta indicates an expected call of AddMeta.
func (mr *MockPastaCacheMockRecorder) AddMeta(ctx, pasta any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddMeta", reflect.TypeOf((*MockPastaCache)(nil).AddMeta), ctx, pasta)
}

// AddText mocks base method.
func (m *MockPastaCache) AddText(ctx context.Context, hash string, data []byte) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddText", ctx, hash, data)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddText indicates an expected call of AddText.
func (mr *MockPastaCacheMockRecorder) AddText(ctx, hash, data any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddText", reflect.TypeOf((*MockPastaCache)(nil).AddText), ctx, hash, data)
}

// GetMeta mocks base method.
func (m *MockPastaCache) GetMeta(ctx context.Context, keyMeta string) (*models.Pasta, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMeta", ctx, keyMeta)
	ret0, _ := ret[0].(*models.Pasta)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetMeta indicates an expected call of GetMeta.
func (mr *MockPastaCacheMockRecorder) GetMeta(ctx, keyMeta any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMeta", reflect.TypeOf((*MockPastaCache)(nil).GetMeta), ctx, keyMeta)
}

// GetText mocks base method.
func (m *MockPastaCache) GetText(ctx context.Context, keyData string) (*string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetText", ctx, keyData)
	ret0, _ := ret[0].(*string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetText indicates an expected call of GetText.
func (mr *MockPastaCacheMockRecorder) GetText(ctx, keyData any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetText", reflect.TypeOf((*MockPastaCache)(nil).GetText), ctx, keyData)
}

// GetViews mocks base method.
func (m *MockPastaCache) GetViews(ctx context.Context, hash string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetViews", ctx, hash)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetViews indicates an expected call of GetViews.
func (mr *MockPastaCacheMockRecorder) GetViews(ctx, hash any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetViews", reflect.TypeOf((*MockPastaCache)(nil).GetViews), ctx, hash)
}

// Views mocks base method.
func (m *MockPastaCache) Views(ctx context.Context, hash string) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Views", ctx, hash)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Views indicates an expected call of Views.
func (mr *MockPastaCacheMockRecorder) Views(ctx, hash any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Views", reflect.TypeOf((*MockPastaCache)(nil).Views), ctx, hash)
}
