// Code generated by MockGen. DO NOT EDIT.
// Source: database.go
//
// Generated by this command:
//
//	mockgen -source=database.go -destination=../mocks/repository/database.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	domain "pastebin/internal/domain/repository"
	models "pastebin/internal/models"
	dto "pastebin/pkg/dto"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockDatabase is a mock of Database interface.
type MockDatabase struct {
	ctrl     *gomock.Controller
	recorder *MockDatabaseMockRecorder
	isgomock struct{}
}

// MockDatabaseMockRecorder is the mock recorder for MockDatabase.
type MockDatabaseMockRecorder struct {
	mock *MockDatabase
}

// NewMockDatabase creates a new mock instance.
func NewMockDatabase(ctrl *gomock.Controller) *MockDatabase {
	mock := &MockDatabase{ctrl: ctrl}
	mock.recorder = &MockDatabaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDatabase) EXPECT() *MockDatabaseMockRecorder {
	return m.recorder
}

// Auth mocks base method.
func (m *MockDatabase) Auth() domain.AuthDatabase {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Auth")
	ret0, _ := ret[0].(domain.AuthDatabase)
	return ret0
}

// Auth indicates an expected call of Auth.
func (mr *MockDatabaseMockRecorder) Auth() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Auth", reflect.TypeOf((*MockDatabase)(nil).Auth))
}

// Pasta mocks base method.
func (m *MockDatabase) Pasta() domain.PastaDatabase {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Pasta")
	ret0, _ := ret[0].(domain.PastaDatabase)
	return ret0
}

// Pasta indicates an expected call of Pasta.
func (mr *MockDatabaseMockRecorder) Pasta() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Pasta", reflect.TypeOf((*MockDatabase)(nil).Pasta))
}

// MockAuthDatabase is a mock of AuthDatabase interface.
type MockAuthDatabase struct {
	ctrl     *gomock.Controller
	recorder *MockAuthDatabaseMockRecorder
	isgomock struct{}
}

// MockAuthDatabaseMockRecorder is the mock recorder for MockAuthDatabase.
type MockAuthDatabaseMockRecorder struct {
	mock *MockAuthDatabase
}

// NewMockAuthDatabase creates a new mock instance.
func NewMockAuthDatabase(ctrl *gomock.Controller) *MockAuthDatabase {
	mock := &MockAuthDatabase{ctrl: ctrl}
	mock.recorder = &MockAuthDatabaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAuthDatabase) EXPECT() *MockAuthDatabaseMockRecorder {
	return m.recorder
}

// CreateUser mocks base method.
func (m *MockAuthDatabase) CreateUser(ctx context.Context, user *dto.RequestNewUser) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateUser", ctx, user)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateUser indicates an expected call of CreateUser.
func (mr *MockAuthDatabaseMockRecorder) CreateUser(ctx, user any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateUser", reflect.TypeOf((*MockAuthDatabase)(nil).CreateUser), ctx, user)
}

// GetHashPassword mocks base method.
func (m *MockAuthDatabase) GetHashPassword(ctx context.Context, email string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetHashPassword", ctx, email)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetHashPassword indicates an expected call of GetHashPassword.
func (mr *MockAuthDatabaseMockRecorder) GetHashPassword(ctx, email any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetHashPassword", reflect.TypeOf((*MockAuthDatabase)(nil).GetHashPassword), ctx, email)
}

// GetUserIDByEmail mocks base method.
func (m *MockAuthDatabase) GetUserIDByEmail(ctx context.Context, email string) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserIDByEmail", ctx, email)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserIDByEmail indicates an expected call of GetUserIDByEmail.
func (mr *MockAuthDatabaseMockRecorder) GetUserIDByEmail(ctx, email any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserIDByEmail", reflect.TypeOf((*MockAuthDatabase)(nil).GetUserIDByEmail), ctx, email)
}

// MockPastaDatabase is a mock of PastaDatabase interface.
type MockPastaDatabase struct {
	ctrl     *gomock.Controller
	recorder *MockPastaDatabaseMockRecorder
	isgomock struct{}
}

// MockPastaDatabaseMockRecorder is the mock recorder for MockPastaDatabase.
type MockPastaDatabaseMockRecorder struct {
	mock *MockPastaDatabase
}

// NewMockPastaDatabase creates a new mock instance.
func NewMockPastaDatabase(ctrl *gomock.Controller) *MockPastaDatabase {
	mock := &MockPastaDatabase{ctrl: ctrl}
	mock.recorder = &MockPastaDatabaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPastaDatabase) EXPECT() *MockPastaDatabaseMockRecorder {
	return m.recorder
}

// AddViews mocks base method.
func (m *MockPastaDatabase) AddViews(ctx context.Context, hash string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddViews", ctx, hash)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddViews indicates an expected call of AddViews.
func (mr *MockPastaDatabaseMockRecorder) AddViews(ctx, hash any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddViews", reflect.TypeOf((*MockPastaDatabase)(nil).AddViews), ctx, hash)
}

// CheckPermission mocks base method.
func (m *MockPastaDatabase) CheckPermission(ctx context.Context, userID int, hash string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CheckPermission", ctx, userID, hash)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CheckPermission indicates an expected call of CheckPermission.
func (mr *MockPastaDatabaseMockRecorder) CheckPermission(ctx, userID, hash any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CheckPermission", reflect.TypeOf((*MockPastaDatabase)(nil).CheckPermission), ctx, userID, hash)
}

// Create mocks base method.
func (m *MockPastaDatabase) Create(ctx context.Context, pasta *models.Pasta) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, pasta)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockPastaDatabaseMockRecorder) Create(ctx, pasta any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockPastaDatabase)(nil).Create), ctx, pasta)
}

// DeleteExpiredPasta mocks base method.
func (m *MockPastaDatabase) DeleteExpiredPasta(ctx context.Context, keys []string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteExpiredPasta", ctx, keys)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteExpiredPasta indicates an expected call of DeleteExpiredPasta.
func (mr *MockPastaDatabaseMockRecorder) DeleteExpiredPasta(ctx, keys any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteExpiredPasta", reflect.TypeOf((*MockPastaDatabase)(nil).DeleteExpiredPasta), ctx, keys)
}

// DeleteMetadata mocks base method.
func (m *MockPastaDatabase) DeleteMetadata(ctx context.Context, hash string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteMetadata", ctx, hash)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteMetadata indicates an expected call of DeleteMetadata.
func (mr *MockPastaDatabaseMockRecorder) DeleteMetadata(ctx, hash any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteMetadata", reflect.TypeOf((*MockPastaDatabase)(nil).DeleteMetadata), ctx, hash)
}

// GetHash mocks base method.
func (m *MockPastaDatabase) GetHash(ctx context.Context, objectID string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetHash", ctx, objectID)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetHash indicates an expected call of GetHash.
func (mr *MockPastaDatabaseMockRecorder) GetHash(ctx, objectID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetHash", reflect.TypeOf((*MockPastaDatabase)(nil).GetHash), ctx, objectID)
}

// GetKey mocks base method.
func (m *MockPastaDatabase) GetKey(ctx context.Context, hash string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetKey", ctx, hash)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetKey indicates an expected call of GetKey.
func (mr *MockPastaDatabaseMockRecorder) GetKey(ctx, hash any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetKey", reflect.TypeOf((*MockPastaDatabase)(nil).GetKey), ctx, hash)
}

// GetKeys mocks base method.
func (m *MockPastaDatabase) GetKeys(ctx context.Context, userID int) ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetKeys", ctx, userID)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetKeys indicates an expected call of GetKeys.
func (mr *MockPastaDatabaseMockRecorder) GetKeys(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetKeys", reflect.TypeOf((*MockPastaDatabase)(nil).GetKeys), ctx, userID)
}

// GetKeysExpiredPasta mocks base method.
func (m *MockPastaDatabase) GetKeysExpiredPasta(ctx context.Context) ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetKeysExpiredPasta", ctx)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetKeysExpiredPasta indicates an expected call of GetKeysExpiredPasta.
func (mr *MockPastaDatabaseMockRecorder) GetKeysExpiredPasta(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetKeysExpiredPasta", reflect.TypeOf((*MockPastaDatabase)(nil).GetKeysExpiredPasta), ctx)
}

// GetManyMetadataByUserID mocks base method.
func (m *MockPastaDatabase) GetManyMetadataByUserID(ctx context.Context, objectID *[]string, userID int) (*[]models.Pasta, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetManyMetadataByUserID", ctx, objectID, userID)
	ret0, _ := ret[0].(*[]models.Pasta)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetManyMetadataByUserID indicates an expected call of GetManyMetadataByUserID.
func (mr *MockPastaDatabaseMockRecorder) GetManyMetadataByUserID(ctx, objectID, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetManyMetadataByUserID", reflect.TypeOf((*MockPastaDatabase)(nil).GetManyMetadataByUserID), ctx, objectID, userID)
}

// GetManyMetadataPublic mocks base method.
func (m *MockPastaDatabase) GetManyMetadataPublic(ctx context.Context, objectID *[]string) (*[]models.Pasta, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetManyMetadataPublic", ctx, objectID)
	ret0, _ := ret[0].(*[]models.Pasta)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetManyMetadataPublic indicates an expected call of GetManyMetadataPublic.
func (mr *MockPastaDatabaseMockRecorder) GetManyMetadataPublic(ctx, objectID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetManyMetadataPublic", reflect.TypeOf((*MockPastaDatabase)(nil).GetManyMetadataPublic), ctx, objectID)
}

// GetMetadata mocks base method.
func (m *MockPastaDatabase) GetMetadata(ctx context.Context, objectID string) (*models.Pasta, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMetadata", ctx, objectID)
	ret0, _ := ret[0].(*models.Pasta)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetMetadata indicates an expected call of GetMetadata.
func (mr *MockPastaDatabaseMockRecorder) GetMetadata(ctx, objectID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMetadata", reflect.TypeOf((*MockPastaDatabase)(nil).GetMetadata), ctx, objectID)
}

// GetPassword mocks base method.
func (m *MockPastaDatabase) GetPassword(ctx context.Context, hash string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPassword", ctx, hash)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPassword indicates an expected call of GetPassword.
func (mr *MockPastaDatabaseMockRecorder) GetPassword(ctx, hash any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPassword", reflect.TypeOf((*MockPastaDatabase)(nil).GetPassword), ctx, hash)
}

// GetVisibility mocks base method.
func (m *MockPastaDatabase) GetVisibility(ctx context.Context, hash string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetVisibility", ctx, hash)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetVisibility indicates an expected call of GetVisibility.
func (mr *MockPastaDatabaseMockRecorder) GetVisibility(ctx, hash any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetVisibility", reflect.TypeOf((*MockPastaDatabase)(nil).GetVisibility), ctx, hash)
}

// IsAccessPrivate mocks base method.
func (m *MockPastaDatabase) IsAccessPrivate(ctx context.Context, userID int, hash string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsAccessPrivate", ctx, userID, hash)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// IsAccessPrivate indicates an expected call of IsAccessPrivate.
func (mr *MockPastaDatabaseMockRecorder) IsAccessPrivate(ctx, userID, hash any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsAccessPrivate", reflect.TypeOf((*MockPastaDatabase)(nil).IsAccessPrivate), ctx, userID, hash)
}

// IsPastaExists mocks base method.
func (m *MockPastaDatabase) IsPastaExists(ctx context.Context, hash string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsPastaExists", ctx, hash)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// IsPastaExists indicates an expected call of IsPastaExists.
func (mr *MockPastaDatabaseMockRecorder) IsPastaExists(ctx, hash any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsPastaExists", reflect.TypeOf((*MockPastaDatabase)(nil).IsPastaExists), ctx, hash)
}

// IsPastaExistsByObjectID mocks base method.
func (m *MockPastaDatabase) IsPastaExistsByObjectID(ctx context.Context, objectID string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsPastaExistsByObjectID", ctx, objectID)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// IsPastaExistsByObjectID indicates an expected call of IsPastaExistsByObjectID.
func (mr *MockPastaDatabaseMockRecorder) IsPastaExistsByObjectID(ctx, objectID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsPastaExistsByObjectID", reflect.TypeOf((*MockPastaDatabase)(nil).IsPastaExistsByObjectID), ctx, objectID)
}

// Paginate mocks base method.
func (m *MockPastaDatabase) Paginate(ctx context.Context, limit, offset int) (*[]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Paginate", ctx, limit, offset)
	ret0, _ := ret[0].(*[]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Paginate indicates an expected call of Paginate.
func (mr *MockPastaDatabaseMockRecorder) Paginate(ctx, limit, offset any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Paginate", reflect.TypeOf((*MockPastaDatabase)(nil).Paginate), ctx, limit, offset)
}

// PaginateByUserID mocks base method.
func (m *MockPastaDatabase) PaginateByUserID(ctx context.Context, limit, offset, userID int) (*[]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PaginateByUserID", ctx, limit, offset, userID)
	ret0, _ := ret[0].(*[]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// PaginateByUserID indicates an expected call of PaginateByUserID.
func (mr *MockPastaDatabaseMockRecorder) PaginateByUserID(ctx, limit, offset, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PaginateByUserID", reflect.TypeOf((*MockPastaDatabase)(nil).PaginateByUserID), ctx, limit, offset, userID)
}
