// Code generated by MockGen. DO NOT EDIT.
// Source: s3.go
//
// Generated by this command:
//
//	mockgen -source=s3.go -destination=../mocks/repository/s3.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	models "pastebin/internal/models"
	dto "pastebin/pkg/dto"
	reflect "reflect"
	time "time"

	gomock "go.uber.org/mock/gomock"
)

// MockS3 is a mock of S3 interface.
type MockS3 struct {
	ctrl     *gomock.Controller
	recorder *MockS3MockRecorder
	isgomock struct{}
}

// MockS3MockRecorder is the mock recorder for MockS3.
type MockS3MockRecorder struct {
	mock *MockS3
}

// NewMockS3 creates a new mock instance.
func NewMockS3(ctrl *gomock.Controller) *MockS3 {
	mock := &MockS3{ctrl: ctrl}
	mock.recorder = &MockS3MockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockS3) EXPECT() *MockS3MockRecorder {
	return m.recorder
}

// Delete mocks base method.
func (m *MockS3) Delete(ctx context.Context, hash string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, hash)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockS3MockRecorder) Delete(ctx, hash any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockS3)(nil).Delete), ctx, hash)
}

// Get mocks base method.
func (m *MockS3) Get(ctx context.Context, key string, password *bool) (*string, *time.Time, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, key, password)
	ret0, _ := ret[0].(*string)
	ret1, _ := ret[1].(*time.Time)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// Get indicates an expected call of Get.
func (mr *MockS3MockRecorder) Get(ctx, key, password any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockS3)(nil).Get), ctx, key, password)
}

// GetFiles mocks base method.
func (m *MockS3) GetFiles(ctx context.Context, objectIDs []string, password *bool) (*[]dto.Entry, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetFiles", ctx, objectIDs, password)
	ret0, _ := ret[0].(*[]dto.Entry)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetFiles indicates an expected call of GetFiles.
func (mr *MockS3MockRecorder) GetFiles(ctx, objectIDs, password any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetFiles", reflect.TypeOf((*MockS3)(nil).GetFiles), ctx, objectIDs, password)
}

// Store mocks base method.
func (m *MockS3) Store(ctx context.Context, owner string, data []byte, isPassword map[string]string) (*models.Pasta, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Store", ctx, owner, data, isPassword)
	ret0, _ := ret[0].(*models.Pasta)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Store indicates an expected call of Store.
func (mr *MockS3MockRecorder) Store(ctx, owner, data, isPassword any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Store", reflect.TypeOf((*MockS3)(nil).Store), ctx, owner, data, isPassword)
}
