
listen:
  port: 8080

storage:
  host: localhost
  port: 5436
  username: postgres
  dbname: test
  password: qwerty
  sslmode: disable

minio:
  host: localhost:9000
  bucket: chukki
  rootuser: root
  password: qwerty
  ssl: false

redis:
  host: localhost:6379

elastic:
  Addresses:
    - localhost:9200
  index: pastas