// Code generated by MockGen. DO NOT EDIT.
// Source: pasta.go
//
// Generated by this command:
//
//	mockgen -source=pasta.go -destination=../mocks/service/pasta.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	models "pastebin/internal/models"
	dto "pastebin/pkg/dto"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockPasta is a mock of Pasta interface.
type MockPasta struct {
	ctrl     *gomock.Controller
	recorder *MockPastaMockRecorder
	isgomock struct{}
}

// MockPastaMockRecorder is the mock recorder for MockPasta.
type MockPastaMockRecorder struct {
	mock *MockPasta
}

// NewMockPasta creates a new mock instance.
func NewMockPasta(ctrl *gomock.Controller) *MockPasta {
	mock := &MockPasta{ctrl: ctrl}
	mock.recorder = &MockPastaMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPasta) EXPECT() *MockPastaMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockPasta) Create(ctx context.Context, req *dto.RequestCreatePasta, userID int) (*models.Pasta, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, req, userID)
	ret0, _ := ret[0].(*models.Pasta)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockPastaMockRecorder) Create(ctx, req, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockPasta)(nil).Create), ctx, req, userID)
}

// Delete mocks base method.
func (m *MockPasta) Delete(ctx context.Context, hash string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, hash)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockPastaMockRecorder) Delete(ctx, hash any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockPasta)(nil).Delete), ctx, hash)
}

// Get mocks base method.
func (m *MockPasta) Get(ctx context.Context, hash string, flag bool) (*models.PastaWithData, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, hash, flag)
	ret0, _ := ret[0].(*models.PastaWithData)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockPastaMockRecorder) Get(ctx, hash, flag any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockPasta)(nil).Get), ctx, hash, flag)
}

// GetText mocks base method.
func (m *MockPasta) GetText(ctx context.Context, keyText, objectID, hash string) (*string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetText", ctx, keyText, objectID, hash)
	ret0, _ := ret[0].(*string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetText indicates an expected call of GetText.
func (mr *MockPastaMockRecorder) GetText(ctx, keyText, objectID, hash any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetText", reflect.TypeOf((*MockPasta)(nil).GetText), ctx, keyText, objectID, hash)
}

// GetVisibility mocks base method.
func (m *MockPasta) GetVisibility(ctx context.Context, hash string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetVisibility", ctx, hash)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetVisibility indicates an expected call of GetVisibility.
func (mr *MockPastaMockRecorder) GetVisibility(ctx, hash any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetVisibility", reflect.TypeOf((*MockPasta)(nil).GetVisibility), ctx, hash)
}

// Paginate mocks base method.
func (m *MockPasta) Paginate(ctx context.Context, rawLimit, rawPage string, hasMetadata bool, userID *int) (*[]dto.TextsWithMetadata, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Paginate", ctx, rawLimit, rawPage, hasMetadata, userID)
	ret0, _ := ret[0].(*[]dto.TextsWithMetadata)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Paginate indicates an expected call of Paginate.
func (mr *MockPastaMockRecorder) Paginate(ctx, rawLimit, rawPage, hasMetadata, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Paginate", reflect.TypeOf((*MockPasta)(nil).Paginate), ctx, rawLimit, rawPage, hasMetadata, userID)
}

// Permission mocks base method.
func (m *MockPasta) Permission(ctx context.Context, hash, password, visibility string, userID int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Permission", ctx, hash, password, visibility, userID)
	ret0, _ := ret[0].(error)
	return ret0
}

// Permission indicates an expected call of Permission.
func (mr *MockPastaMockRecorder) Permission(ctx, hash, password, visibility, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Permission", reflect.TypeOf((*MockPasta)(nil).Permission), ctx, hash, password, visibility, userID)
}
