// Code generated by MockGen. DO NOT EDIT.
// Source: elastic.go
//
// Generated by this command:
//
//	mockgen -source=elastic.go -destination=../mocks/repository/elastic.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockElastic is a mock of Elastic interface.
type MockElastic struct {
	ctrl     *gomock.Controller
	recorder *MockElasticMockRecorder
	isgomock struct{}
}

// MockElasticMockRecorder is the mock recorder for MockElastic.
type MockElasticMockRecorder struct {
	mock *MockElastic
}

// NewMockElastic creates a new mock instance.
func NewMockElastic(ctrl *gomock.Controller) *MockElastic {
	mock := &MockElastic{ctrl: ctrl}
	mock.recorder = &MockElasticMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockElastic) EXPECT() *MockElasticMockRecorder {
	return m.recorder
}

// NewIndex mocks base method.
func (m *MockElastic) NewIndex(text []byte, key, index string, tags []string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NewIndex", text, key, index, tags)
	ret0, _ := ret[0].(error)
	return ret0
}

// NewIndex indicates an expected call of NewIndex.
func (mr *MockElasticMockRecorder) NewIndex(text, key, index, tags any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NewIndex", reflect.TypeOf((*MockElastic)(nil).NewIndex), text, key, index, tags)
}

// SearchWord mocks base method.
func (m *MockElastic) SearchWord(word, index string) ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SearchWord", word, index)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SearchWord indicates an expected call of SearchWord.
func (mr *MockElasticMockRecorder) SearchWord(word, index any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SearchWord", reflect.TypeOf((*MockElastic)(nil).SearchWord), word, index)
}
